version: "3.8"
services:
  db:
    image: postgres:16
    container_name: localshare_postgres
    restart: always
    environment:
      POSTGRES_USER: localshare
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: localshare
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: localshare_app
    command: ["npm", "run", "start"]
    env_file:
      - .env.prod
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    ports:
      - "3000:3000"
